<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>All_Test_Cases_of_Counts</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>519ec677-927a-449c-8ed2-972246983170</testSuiteGuid>
   <testCaseLink>
      <guid>133d5bf0-5768-4d5a-a029-88922545374e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Check_BO_Count</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c39d4407-8eb4-4890-8e36-ae8c01271778</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9862f4a5-f6b3-4d13-b94d-79964ce2ab7f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Check_BO_Col_Count</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4baa237-7f84-437f-be39-726eba229e09</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>313fc0f7-46f7-47e4-a2b7-3441b33323d7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Check_BO_Query_Count</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>27b27655-bf96-4e0c-9923-9caa8987a1ff</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8e21d23a-4138-43c0-88ba-d23c0443312f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Check_BO_Query_Grp_Count</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6490c9d4-7bfc-4caa-b7e7-94ac09895c1f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d762a52c-6da8-4a73-881a-e417acad84b4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Check_Landing_Count</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>449cf3b4-5d8c-4fbf-ad6f-43cbf76426c8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f65a58b3-156f-4c12-8ca7-d124bef498e9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Check_Landing_Col_Count</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4364107a-8144-40b0-8903-600bee50f11c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a18fff5b-90a3-48e8-94c4-6edd70b1d32f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Check_STG_Count</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf0bdfcb-8c22-4690-8396-a9b067c09840</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6569a5b6-8d9e-4feb-91f5-9e576a3dbd6d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Check_STG_Col_Count</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>261183fb-700e-41ce-a12b-55c248620273</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>207dfafa-5801-4877-ab93-d53f4ea50298</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Check_BG_Count</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8fcaffa-ef73-4346-a135-b313421e5e12</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8840c830-b122-48cd-b3fb-3b4a33a8b610</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Check_BO_SQL_Count</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f0ba5ef-0b18-4c46-80df-2b918c3996f6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c4907863-c813-4ea9-a66a-c7b8bfa54407</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Check_Mtch_Col_Count</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f8efc521-b4e4-4cf8-b6e7-da728b9fe246</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a7c86333-f82f-4c08-b9d2-a902741a97a8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Check_Mtch_Fuzzy_Count</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ffe862a1-13bf-482b-8105-311b9083f496</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c4fdc5f4-166f-4b4e-b7da-2c6852278445</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Check_Mtch_Path_Count</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8cf9193f-ad51-4cfb-bf9c-8bb36c5babc1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>37c63417-0762-4a2b-936d-444f5663b88c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Check_PCKG_Count</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>16274769-ed61-46b4-b4e6-d4384788d7dc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8872f8e6-69f1-4e93-be34-b72e55704438</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Check_SRC_Sys_Count</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e2d835e7-3e3a-43f0-9cd5-5878b87cf68d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>488015e0-78c4-4fb2-acff-c840cbc9dcf8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Check_SRC_Trust_Count</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a1153128-ce2b-4d81-afe8-61f6dbcc246b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
